[[plugins]]
repository = 'tpope/vim-endwise'
filetypes = ['ruby']

[[plugins]]
repository = 'tpope/vim-rails'
filetypes = ['ruby']

[[plugins]]
repository = 'vim-scripts/ruby-matchit'
filetypes = ['ruby']
