[[plugins]]
repo = 'Shougo/vimproc.vim'

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mac.mak'
  unix = 'make -f make_unix.mak'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = "tyru/caw.vim"

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'metakirby5/codi.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
