[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = ['ruby']

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['coffee', 'haskell', 'html', 'javascript', 'json', 'ruby', 'scss', 'sh', 'vim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
