[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'mkasa/neco-ghc-lushtags'
on_ft = ['haskell']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite']

[[plugins]]
repo = 'tsukkee/unite-tag'
on_cmd = ['Unite']

[[plugins]]
repo = 'thoughtbot/vim-rspec'
depends = ['vim-dispatch']
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'haml']

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_i = 1

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
on_ft = ['html', 'haml']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = ['proto']

[[plugins]]
repo = 'vim-scripts/vim-stylus'
on_ft = ['stylus']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
