return require('packer').startup(function(use)
  use({ 'cespare/vim-toml', ft = { 'toml' } })
  use({ 'delphinus/vim-auto-cursorline' })
  use({ 'digitaltoad/vim-pug' })
  use({ 'easymotion/vim-easymotion' })
  use({ 'editorconfig/editorconfig-vim' })
  use({ 'hashivim/vim-terraform' })
  use({ 'haskell/haskell-ide-engine', ft = { 'haskell' } })
  use({ 'itchyny/lightline.vim' })
  use({ 'itchyny/vim-cursorword' })
  use({ 'itchyny/vim-parenmatch' })
  use({ 'junegunn/fzf' })
  use({ 'junegunn/fzf.vim' })
  use({ 'junegunn/vim-peekaboo' })
  use({ 'kana/vim-smartinput' })
  use({ 'kshenoy/vim-signature' })
  use({ 'LnL7/vim-nix' })
  use({ 'mattn/emmet-vim', ft = { 'html', 'typescript.tsx' } })
  use({ 'metakirby5/codi.vim' })
  use({ 'neoclide/coc.nvim', run = 'yarn install' })
  use({ 'neovimhaskell/haskell-vim', ft = { 'haskell' } })
  use({ 'othree/html5.vim', ft = { 'html' } })
  use({ 'purescript-contrib/purescript-vim', ft = { 'purescript' } })
  use({ 'rust-lang/rust.vim', ft = { 'rust' } })
  use({ 'scrooloose/nerdtree', cmd = { 'NERDTreeFind', 'NERDTreeToggle' } })
  use({ 'Shougo/vimfiler.vim' })
  use({ 'SirVer/ultisnips' })
  use({ 'thinca/vim-quickrun' })
  use({ 'tomasr/molokai' })
  use({ 'tpope/vim-fugitive' })
  use({ 'tpope/vim-surround' })
  use({ 'tyru/caw.vim' })
  use({ 'vim-scripts/vim-stylus', ft = { 'stylus' } })
  use({ 'Xuyuanp/nerdtree-git-plugin', cmd = { 'NERDTreeToggle' } })
end)
